# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tadd Mencer
email: taddmencer01@gmail.com
description: Look at all this awesome text about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: taddmencer
github_username:  taddmencer

social:
  name: Tadd Mencer
  links:
    - https://twitter.com/taddmencer
    - https://www.linkedin.com/in/taddmencer/
    - https://github.com/taddmencer
    - https://plus.google.com/u/0/+TaddMencer

author: taddmencer

webmaster_verification:
  google: rOjNEn5n34YuQErB67xJAnL5oxUS0y53d4ft6VtAyjE

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap #https://github.com/jekyll/jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
