#Site Settings
title: Tadd Mencer
author: Tadd Mencer
description: ""
url: "http://taddmencer.com"
author:
  name: "Tadd Mencer"
  email: "tadd@cubelabmedia.com"
  url: "http://taddmencer.com"

version: "1.0"

#Build Settings
baseurl: "/"
markdown: kramdown
source: .
destination: ./site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
- jekyll-feed
- jekyll-menus
- jekyll-paginate
