title:             Tadd Mencer
email:             taddmencer01@gmail.com
description:       It's my website and I'll cry if I want to.
author:            Tadd Mencer
baseurl:           "/"
url:               "http://taddmencer.github.io"

# Social Profiles
twitter_username:  taddmencer
github_username:   taddmencer
facebook_username: 
kofi_username: L3L7MTF3

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
