---
title: Tadd Mencer
author: Forestry.io
email: tadd@cubelabmedia.com
description: ''
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope: ''
  values: ''
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
